// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6Z-qPfitdSNonUT3_Ij1ATLf3DMSSEeE',
    appId: '1:80028729182:web:96075ffaff17883cc619cf',
    messagingSenderId: '80028729182',
    projectId: 'cmmc-6aad1',
    authDomain: 'cmmc-6aad1.firebaseapp.com',
    storageBucket: 'cmmc-6aad1.firebasestorage.app',
    measurementId: 'G-W1C8EM2DLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKbW0cj6bBd-ggDxjbvVyP0DzUDcHmhaY',
    appId: '1:80028729182:android:a9b68b22fb295c7bc619cf',
    messagingSenderId: '80028729182',
    projectId: 'cmmc-6aad1',
    storageBucket: 'cmmc-6aad1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6Z-qPfitdSNonUT3_Ij1ATLf3DMSSEeE',
    appId: '1:80028729182:web:9a346ce09a61bfbdc619cf',
    messagingSenderId: '80028729182',
    projectId: 'cmmc-6aad1',
    authDomain: 'cmmc-6aad1.firebaseapp.com',
    storageBucket: 'cmmc-6aad1.firebasestorage.app',
    measurementId: 'G-M6MR98BZ44',
  );
}
